name: CI

on:
  push:
  pull_request:

jobs:
  tests:
    runs-on: ubuntu-latest

    env:
      PATH_TO_LIBCLANG: /usr/lib/x86_64-linux-gnu/libclang-17.so

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: '3.10'

      - name: Install Clang
        run: sudo apt install clang libclang-17-dev

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest pylint
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Generate coverage report
        run: coverage run --include=src/* -m pytest .

      - name: Show coverage report
        run: coverage report -m

  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest pylint
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Run PyLint
        run: pylint ./src